//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bendoAppDesktop.DbContextEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.productos = new HashSet<producto>();
        }
    
        public long id_categoria { get; set; }
        public string categoria1 { get; set; }
        public long usuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public long usuario_modificacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public int estatus { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual ICollection<producto> productos { get; set; }
    }
}
