//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bendoAppDesktop.DbContextEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.ventas = new HashSet<venta>();
        }
    
        public long id_cliente { get; set; }
        public string nombre_completo { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public decimal lim_credito { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public long usuario_alta { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public long usuario_modificacion { get; set; }
        public int estatus { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual ICollection<venta> ventas { get; set; }
    }
}
