//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bendoAppDesktop.DbContextEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bendo_puntoventaEntities : DbContext
    {
        public bendo_puntoventaEntities()
            : base("bendo_puntoventaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<caja> cajas { get; set; }
        public DbSet<categoria> categorias { get; set; }
        public DbSet<cliente> clientes { get; set; }
        public DbSet<detalle_venta> detalle_venta { get; set; }
        public DbSet<estatus_venta> estatus_venta { get; set; }
        public DbSet<kits_paquetes> kits_paquetes { get; set; }
        public DbSet<modulo> modulos { get; set; }
        public DbSet<operacione> operaciones { get; set; }
        public DbSet<operaciones_modulos> operaciones_modulos { get; set; }
        public DbSet<producto> productos { get; set; }
        public DbSet<unidades_medida> unidades_medida { get; set; }
        public DbSet<usuario> usuarios { get; set; }
        public DbSet<venta> ventas { get; set; }
    }
}
