//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bendoAppDesktop.DbContextEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_venta
    {
        public long id_vta_detalle { get; set; }
        public long id_venta { get; set; }
        public long id_producto { get; set; }
        public decimal precio { get; set; }
        public decimal cantidad { get; set; }
        public decimal importe { get; set; }
        public decimal descuento { get; set; }
    
        public virtual venta venta { get; set; }
        public virtual producto producto { get; set; }
    }
}
