//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bendoAppDesktop.DbContextEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class operaciones_modulos
    {
        public long id { get; set; }
        public long id_usuario { get; set; }
        public long id_modulo { get; set; }
        public long id_operacion { get; set; }
        public int activo { get; set; }
    
        public virtual modulo modulo { get; set; }
        public virtual operacione operacione { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
