//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bendoAppDesktop.DbContextEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidades_medida
    {
        public unidades_medida()
        {
            this.productos = new HashSet<producto>();
        }
    
        public long id_unidad { get; set; }
        public string unidad_medida { get; set; }
    
        public virtual ICollection<producto> productos { get; set; }
    }
}
