//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bendoAppDesktop.DbContextEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.categorias = new HashSet<categoria>();
            this.categorias1 = new HashSet<categoria>();
            this.clientes = new HashSet<cliente>();
            this.clientes1 = new HashSet<cliente>();
            this.operaciones_modulos = new HashSet<operaciones_modulos>();
            this.ventas = new HashSet<venta>();
        }
    
        public long id_usuario { get; set; }
        public string nombre_completo { get; set; }
        public string usuario1 { get; set; }
        public int is_administrador { get; set; }
        public long usuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public long usuario_modificacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public int estatus { get; set; }
    
        public virtual ICollection<categoria> categorias { get; set; }
        public virtual ICollection<categoria> categorias1 { get; set; }
        public virtual ICollection<cliente> clientes { get; set; }
        public virtual ICollection<cliente> clientes1 { get; set; }
        public virtual ICollection<operaciones_modulos> operaciones_modulos { get; set; }
        public virtual ICollection<venta> ventas { get; set; }
    }
}
