//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bendoAppDesktop.DbContextEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.detalle_venta = new HashSet<detalle_venta>();
        }
    
        public long id_folio { get; set; }
        public string ticket { get; set; }
        public long id_cliente { get; set; }
        public long id_usuario { get; set; }
        public long id_caja { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public System.TimeSpan hora_venta { get; set; }
        public int total_articulos { get; set; }
        public decimal total { get; set; }
        public decimal pago { get; set; }
        public long estatus_venta { get; set; }
    
        public virtual caja caja { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
        public virtual estatus_venta estatus_venta1 { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
